### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/rich-search-addon#2]
- Explain what the component can do out-of-the-box and what with additional programming
- Explain what are main components and how they interact: search field, SearchStrategy, SearchContext, etc.
- In "Main Screen Configuration" (which can probably be renamed to "Quick Start"), remove all unneeded from the XML descriptor and keep only the meaningful part like this:
    ```
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
            class="com.company.testrichsearch.web.screens.ExtAppMainWindow"
            extends="/com/haulmont/cuba/web/app/mainwindow/mainwindow.xml"
            messagesPack="com.company.testrichsearch.web.screens"
            xmlns:ext="http://schemas.haulmont.com/cuba/window-ext.xsd"
            xmlns:search="http://schemas.haulmont.com/cuba/search.xsd">
        <layout>
            <hbox id="titleBar">
                <hbox id="mainButtonsBox"
                    ext:index="2"
                    spacing="true">
                    <search:richSearch id="search"
                                    align="MIDDLE_LEFT"
                                    inputPrompt="Search..."
                                    suggestionsLimit="200">
                        <search:strategyBean name="search_MainMenuSearchStrategy"/>
                    </search:richSearch>
                </hbox>
            </hbox>
        </layout>
    </window>
    ```
- "Usage" section is too concise and confusing:
  - "Using Declarative XML Strategy" - confusing. It's actually a way to define a strategy as a Spring bean.
  - "Configuration of references for frame methods" - confusing. It's a way to use controller methods instead of implementing the strategy interface.

- Fix typos: "If a custom theme is used in your project, aff the following stypes"

**Comment by zharenov** [comment]
The readme is updated.
