### ISSUE TITLE
Upgrade add-on to CUBA 7.2 platform version

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/rich-search-addon#8]
Upgrade to CUBA 7.2-SNAPSHOT

**Comment by mariodavid** [comment]
hi,

do you have a timeline for the 7.2 update? Is there anything I can help you with? I want to update the instant-launcher addon as well and as this addon depends on rich-search I'm now stuck :)

Just let me know if there is anything I can do...

Cheers
Mario
